# Generated by Django 6.0.1 on 2026-01-28 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CategoryName', models.CharField(max_length=255)),
                ('CategoryDescription', models.TextField()),
                ('CreationDate', models.DateTimeField()),
                ('UpdationDate', models.DateTimeField()),
            ],
        ),
    ]
