# Generated by Django 6.0.1 on 2026-01-28 05:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='CreationDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='UpdationDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductName', models.CharField(max_length=255)),
                ('ProductPrice', models.FloatField()),
                ('ProductDiscountPrice', models.FloatField()),
                ('ShortDescription', models.TextField()),
                ('LongDescription', models.TextField()),
                ('ProductImage1', models.ImageField(upload_to='productsimages/')),
                ('ProductImage2', models.ImageField(upload_to='productsimages/')),
                ('ProductImage3', models.ImageField(upload_to='productsimages/')),
                ('ProductFile', models.FileField(upload_to='productsFile/')),
                ('CreationDate', models.DateTimeField(auto_now_add=True)),
                ('UpdationDate', models.DateTimeField(auto_now_add=True)),
                ('CategoryId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productsimages.category')),
            ],
        ),
    ]
