# Generated by Django 6.0.1 on 2026-01-28 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_category_creationdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ProductImage1',
            field=models.ImageField(upload_to='productsimages/productsimages/'),
        ),
    ]
