# Generated by Django 6.0.1 on 2026-01-30 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_productimage1'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='DemoFolder',
            field=models.CharField(blank=True, help_text='Auto-generated demo folder name', max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='ProductFile',
            field=models.FileField(upload_to='productsimages/productsFile/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='ProductImage2',
            field=models.ImageField(upload_to='productsimages/productsimages/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='ProductImage3',
            field=models.ImageField(upload_to='productsimages/productsimages/'),
        ),
    ]
