# Generated by Django 6.0.1 on 2026-01-30 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_demofolder_alter_product_productfile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='CategoryId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='ProductFile',
            field=models.FileField(upload_to='products/productsFile/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='ProductImage1',
            field=models.ImageField(upload_to='products/productsimages/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='ProductImage2',
            field=models.ImageField(upload_to='products/productsimages/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='ProductImage3',
            field=models.ImageField(upload_to='products/productsimages/'),
        ),
    ]
